# Generated by Django 5.1.11 on 2025-07-03 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyscada', '0110_variable_readable'),
        ('systemstat', '0019_alter_systemstatvariable_information'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimestampDataSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datasource', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pyscada.datasource')),
            ],
        ),
    ]